# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dce8ceb683aa96b532ef77b71f1a9cbe52bf50364b4e48207bc1c05c7a5a4c55a9624dd6bfb4f04030210512002bce5b18757159de1074a1b5a5e3b3595a5a18
  mandrill_api_key: h6Pw7TxQ1EAr_WqflmsVpg
  mandrill_user_name: kloffelin08@rambler.ru

staging:
  secret_key_base: 3a400067d0ab3c9e8196e3be9107bf4ee1ede9615e17667d3ec3ccb6077136f970ae120369dc2e31d45b97ff4bfe2732817a71cb982781f0569aeba6b25cac8b
  mandrill_api_key: h6Pw7TxQ1EAr_WqflmsVpg
  mandrill_user_name: kloffelin08@rambler.ru

test:
  secret_key_base: 71b19de312c05aca98208b3f14d6fd11c7906c09dc90d40c335af215395561f6ef7ebecdfc70eb26f5a927eef5ad14ab1aed1e5c611d8e2655bc4598fec065b9
  mandrill_api_key: h6Pw7TxQ1EAr_WqflmsVpg
  mandrill_user_name: kloffelin08@rambler.ru

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
